version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - database
      - php-fpm
  php-fpm:
    build:
      context: "./docker"
      dockerfile: "php/Dockerfile"
    volumes:
      - ./:/var/www/html/
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    restart: always
  database:
    image: postgres
    restart: always
    ports:
      - ${DB_LOCAL_PORT}:5433
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: ${DB_INTERNAL_DATA_PATH};/var/lib/postgresql/data
    volumes:
      - ${DB_LOCAL_DATA_PATH}:${DB_INTERNAL_DATA_PATH}
  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_LOCAL_PORT}:8080

