version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - database
      - php-fpm
  php-fpm:
    build:
      context: "./docker"
      dockerfile: "php/Dockerfile"
    volumes:
      - ./:/var/www/html/
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    restart: always
  database:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - db-volume:/var/lib/mysql
    restart: always

volumes:
  db-volume:
