security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Domain\Entity\User\User
                property: email
    firewalls:
        dev:
            pattern: ^/_(profiler|wdt)
            security: false
        api:
            pattern: ^/api/
            stateless: true
            provider: app_user_provider
            entry_point: App\Infrastructure\Security\AuthenticationEntryPoint
            access_denied_handler: App\Infrastructure\Security\AccessDeniedHandler
            custom_authenticators:
                - App\Infrastructure\Security\ApiKeyAuthenticator
        main:
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
