default:
    path: /
    controller: App\UserInterface\API\Action\DefaultAction

api.user.login:
    path: /api/user/login
    controller: App\UserInterface\API\Action\User\LoginAction
    methods: ['POST']
