parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

        bind:

    App\:
        resource: '../Application'
        exclude:
            - '../Application/DependencyInjection/'
            - '../Application/Entity/'
            - '../Application/Kernel.php'

    App\UserInterface\API\Action\:
        resource: '../Application/UserInterface/API/Action'
        tags:
            - 'controller.service_arguments'
